# Theme and status bar styling.

run-shell "~/.config/tmux/scripts/update_theme_color.sh"

set -g pane-border-style fg=colour244
set -g pane-active-border-style fg=orange

set -g status on
set -g status-interval 1
set -g status-justify left
set -g status-left-length 90
set -g status-right-length 80
set -g status-bg black

setw -g window-status-separator ""
setw -g window-status-format         "#[fg=#c5c8c6] #W "
setw -g window-status-current-format "#[fg=#{@theme_color},bold] #W "

set -g status-left  "#(~/.config/tmux/tmux-status/left.sh #{q:session_id} #{q:session_name} #{q:client_width} #{q:status-bg})"
set -g status-right "#[fg=#c5c8c6] %Y-%m-%d %a #[fg=#{@theme_color},bold]%H:%M "
